[package]
name = "swh-subgrapher"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bitvec = "1.0.1"
clap = "4.5.37"
dsi-progress-logger = "0.8.1"
env_logger = "0.11.8"
hex = "0.4.3"
log = "0.4.27"
sha1 = "0.10.6"
swh-graph = "6.7.0"
